import mysql from "mysql2/promise";
import fs from "fs";

const dbConfig = {
  host: process.env.MYSQL_HOST || "localhost",
  port: Number(process.env.MYSQL_PORT || 3306),
  user: process.env.MYSQL_USER || "root",
  password: process.env.MYSQL_PASSWORD || "12345",
  database: process.env.MYSQL_DATABASE || "atom_trainer_hub",
};

const INITIAL_TRAINERS = [
  {
    id: "1",
    code: "ATM-T-001",
    name: "Rahul Sharma",
    designation: "Senior Java Trainer",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Rahul%20Sharma&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012301",
    whatsapp: "+919845012301",
    email: "rahul.sharma@example.com",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    organization: "Independent Consultant",
    experience: 8,
    trainingExperience: 6,
    trainerType: "Technical Trainer",
    employment: "Freelance",
    modes: ["Online", "Offline"],
    availability: "available",
    rating: 4.7,
    projectsCompleted: 24,
    bio: "Java full-stack trainer with deep Spring Boot and DSA expertise. Delivered 100+ corporate and campus programs.",
    status: "Active",
    tags: ["Top Rated", "Java Expert", "Bangalore"],
    skills: [
      { name: "Java", level: "Expert", years: 8 },
      { name: "Spring Boot", level: "Expert", years: 6 },
      { name: "DSA", level: "Advanced", years: 7 },
      { name: "SQL", level: "Advanced", years: 6 },
      { name: "Microservices", level: "Advanced", years: 4 },
    ],
    softSkills: ["Communication", "Interview Skills"],
    education: [
      { degree: "B.E.", specialization: "Computer Science", university: "VTU", year: 2014 },
    ],
    certifications: [
      {
        name: "Oracle Certified Professional: Java SE 11",
        org: "Oracle",
        id: "OCP-77120",
        issued: "2021-03-10",
        expires: "2027-03-10",
      },
    ],
    trainings: [
      {
        client: "ABC University",
        program: "Java Full Stack Bootcamp",
        tech: "Java, Spring Boot",
        students: 120,
        days: 15,
        location: "Bangalore",
        mode: "Offline",
        year: 2025,
        rating: 4.8,
      },
      {
        client: "Nexa Systems",
        program: "Microservices Upskilling",
        tech: "Spring Cloud",
        students: 40,
        days: 6,
        location: "Pune",
        mode: "Hybrid",
        year: 2024,
        rating: 4.6,
      },
    ],
    notes: [
      { note: "Excellent for Java DSA programs.", by: "Admin", date: "2026-04-02" },
      { note: "Prefers Bangalore and Mysore projects.", by: "HR", date: "2026-05-19" },
    ],
    documents: [],
    sectors: ["University", "Corporate"],
    addedOn: "2026-01-15",
  },
  {
    id: "2",
    code: "ATM-T-002",
    name: "Priya Nair",
    designation: "Python & Data Science Trainer",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Priya%20Nair&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012302",
    whatsapp: "+919845012302",
    email: "priya.nair@example.com",
    city: "Mysore",
    state: "Karnataka",
    country: "India",
    organization: "Independent",
    experience: 7,
    trainingExperience: 5,
    trainerType: "Technical Trainer",
    employment: "Freelance",
    modes: ["Online", "Offline"],
    availability: "partial",
    availableFrom: "2026-09-15",
    availableUntil: "2026-09-30",
    rating: 4.8,
    projectsCompleted: 19,
    bio: "Data science trainer specialising in Python, ML pipelines and analytics for campus and corporate batches.",
    status: "Active",
    tags: ["Python Expert", "Top Rated"],
    skills: [
      { name: "Python", level: "Expert", years: 7 },
      { name: "Machine Learning", level: "Expert", years: 5 },
      { name: "Data Science", level: "Advanced", years: 5 },
      { name: "Pandas", level: "Expert", years: 6 },
      { name: "TensorFlow", level: "Intermediate", years: 3 },
      { name: "SQL", level: "Advanced", years: 5 },
    ],
    softSkills: ["Communication"],
    education: [
      { degree: "M.Tech", specialization: "Data Science", university: "NIT Trichy", year: 2016 },
    ],
    certifications: [
      {
        name: "TensorFlow Developer",
        org: "Google",
        id: "TFD-3391",
        issued: "2023-01-20",
        expires: "2026-10-20",
      },
    ],
    trainings: [
      {
        client: "Sri Vidya College",
        program: "AI/ML Bootcamp",
        tech: "Python, ML",
        students: 90,
        days: 10,
        location: "Mysore",
        mode: "Offline",
        year: 2025,
        rating: 4.9,
      },
    ],
    notes: [
      {
        note: "Strong student engagement, great for beginner batches.",
        by: "Admin",
        date: "2026-03-11",
      },
    ],
    documents: [],
    sectors: ["College", "Corporate"],
    addedOn: "2026-02-01",
  },
  {
    id: "3",
    code: "ATM-T-003",
    name: "Arjun Menon",
    designation: "MERN Stack Trainer",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Arjun%20Menon&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012303",
    whatsapp: "+919845012303",
    email: "arjun.menon@example.com",
    city: "Kochi",
    state: "Kerala",
    country: "India",
    organization: "Independent",
    experience: 5,
    trainingExperience: 4,
    trainerType: "Technical Trainer",
    employment: "Freelance",
    modes: ["Online", "Offline"],
    availability: "available",
    rating: 4.4,
    projectsCompleted: 12,
    bio: "Full stack JavaScript trainer specialising in React, Node, Express, MongoDB and modern REST API development.",
    status: "Active",
    tags: ["MERN", "React"],
    skills: [
      { name: "React", level: "Advanced", years: 5 },
      { name: "Node.js", level: "Advanced", years: 4 },
      { name: "JavaScript", level: "Expert", years: 5 },
      { name: "MERN", level: "Advanced", years: 4 },
      { name: "SQL", level: "Intermediate", years: 3 },
    ],
    softSkills: ["Communication"],
    education: [{ degree: "B.Tech", specialization: "IT", university: "CUSAT", year: 2018 }],
    certifications: [],
    trainings: [],
    notes: [],
    documents: [],
    sectors: ["College", "University"],
    addedOn: "2026-02-15",
  },
  {
    id: "4",
    code: "ATM-T-004",
    name: "Vikram Mehta",
    designation: "Cloud & DevOps Trainer",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Vikram%20Mehta&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012304",
    whatsapp: "+919845012304",
    email: "vikram.mehta@example.com",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    organization: "Independent",
    experience: 10,
    trainingExperience: 7,
    trainerType: "Technical Trainer",
    employment: "Freelance",
    modes: ["Online", "Offline", "Hybrid"],
    availability: "available",
    rating: 4.9,
    projectsCompleted: 31,
    bio: "AWS authorized instructor and DevOps architect with hands-on enterprise deployment experience.",
    status: "Active",
    tags: ["AWS Certified", "DevOps Pro", "Top Rated"],
    skills: [
      { name: "AWS", level: "Expert", years: 8 },
      { name: "DevOps", level: "Expert", years: 7 },
      { name: "Linux", level: "Expert", years: 10 },
      { name: "Cloud", level: "Expert", years: 9 },
    ],
    softSkills: ["Leadership", "Communication"],
    education: [
      { degree: "B.E.", specialization: "ECE", university: "Osmania University", year: 2013 },
    ],
    certifications: [
      {
        name: "AWS Solutions Architect Professional",
        org: "AWS",
        id: "AWS-PSA-9901",
        issued: "2022-06-15",
        expires: "2027-06-15",
      },
    ],
    trainings: [],
    notes: [],
    documents: [],
    sectors: ["Corporate", "University"],
    addedOn: "2026-01-10",
  },
  {
    id: "5",
    code: "ATM-T-005",
    name: "Sneha Kulkarni",
    designation: "Aptitude & Soft Skills Trainer",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Sneha%20Kulkarni&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012305",
    whatsapp: "+919845012305",
    email: "sneha.kulkarni@example.com",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    organization: "Independent",
    experience: 6,
    trainingExperience: 6,
    trainerType: "Soft Skills Trainer",
    employment: "Freelance",
    modes: ["Offline", "Online"],
    availability: "available",
    rating: 4.6,
    projectsCompleted: 28,
    bio: "Specialist in quantitative aptitude, logical reasoning, verbal ability, and corporate transition skills for engineering graduates.",
    status: "Active",
    tags: ["Aptitude Specialist", "Campus Placement Expert"],
    skills: [
      { name: "Aptitude", level: "Expert", years: 6 },
      { name: "Soft Skills", level: "Expert", years: 6 },
      { name: "Communication", level: "Expert", years: 6 },
      { name: "Interview Skills", level: "Expert", years: 5 },
      { name: "Leadership", level: "Advanced", years: 4 },
    ],
    softSkills: ["Communication", "Soft Skills", "Leadership", "Aptitude"],
    education: [
      {
        degree: "MBA",
        specialization: "HR & Marketing",
        university: "Pune University",
        year: 2017,
      },
    ],
    certifications: [
      { name: "Certified Life Skills Trainer", org: "ICF", id: "ICF-7782", issued: "2021-08-10" },
    ],
    trainings: [],
    notes: [],
    documents: [],
    sectors: ["College", "University", "School"],
    addedOn: "2026-02-10",
  },
  {
    id: "6",
    code: "ATM-T-006",
    name: "Karthik Raghavan",
    designation: "Campus Placement Readiness & Aptitude Lead",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Karthik%20Raghavan&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012306",
    whatsapp: "+919845012306",
    email: "karthik.raghavan@example.com",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    organization: "Independent",
    experience: 8,
    trainingExperience: 7,
    trainerType: "Aptitude Trainer",
    employment: "Freelance",
    modes: ["Offline", "Online", "Hybrid"],
    availability: "available",
    rating: 4.9,
    projectsCompleted: 42,
    bio: "Master trainer in Quantitative Aptitude, Logical Reasoning, GDs and Mock Technical/HR Interviews for top Tier-1 & Tier-2 engineering colleges.",
    status: "Active",
    tags: ["Top Placement Trainer", "Aptitude", "Soft Skills", "Bangalore"],
    skills: [
      { name: "Aptitude", level: "Expert", years: 8 },
      { name: "Logical Reasoning", level: "Expert", years: 8 },
      { name: "Soft Skills", level: "Expert", years: 7 },
      { name: "Interview Skills", level: "Expert", years: 8 },
      { name: "Communication", level: "Expert", years: 7 },
    ],
    softSkills: ["Aptitude", "Soft Skills", "Communication", "Leadership"],
    education: [
      { degree: "B.Tech", specialization: "Mechanical", university: "NIT Surathkal", year: 2015 },
    ],
    certifications: [
      {
        name: "Advanced Aptitude Master Trainer",
        org: "TMI",
        id: "TMI-9912",
        issued: "2020-04-12",
      },
    ],
    trainings: [
      {
        client: "RV College of Engineering",
        program: "Campus Placement Aptitude Bootcamp",
        tech: "Aptitude, Soft Skills",
        students: 350,
        days: 12,
        location: "Bangalore",
        mode: "Offline",
        year: 2025,
        rating: 4.95,
      },
    ],
    notes: [
      {
        note: "Ranked #1 for pre-placement aptitude drives in Karnataka.",
        by: "Admin",
        date: "2026-06-01",
      },
    ],
    documents: [],
    sectors: ["College", "University"],
    addedOn: "2026-01-05",
  },
  {
    id: "7",
    code: "ATM-T-007",
    name: "Dr. Ananya Mukherjee",
    designation: "AI/ML & Generative AI Specialist",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Dr.%20Ananya%20Mukherjee&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012307",
    whatsapp: "+919845012307",
    email: "ananya.mukherjee@example.com",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    organization: "Independent",
    experience: 9,
    trainingExperience: 6,
    trainerType: "Domain Expert",
    employment: "Freelance",
    modes: ["Online", "Offline"],
    availability: "available",
    rating: 4.85,
    projectsCompleted: 22,
    bio: "PhD in Machine Learning. Conducts faculty development programs and corporate hands-on GenAI workshops.",
    status: "Active",
    tags: ["PhD", "GenAI", "Machine Learning"],
    skills: [
      { name: "AI", level: "Expert", years: 8 },
      { name: "Machine Learning", level: "Expert", years: 8 },
      { name: "Python", level: "Expert", years: 9 },
      { name: "TensorFlow", level: "Expert", years: 7 },
      { name: "Data Science", level: "Expert", years: 8 },
    ],
    softSkills: ["Communication", "Leadership"],
    education: [
      {
        degree: "PhD",
        specialization: "Machine Learning",
        university: "IIT Kharagpur",
        year: 2016,
      },
    ],
    certifications: [],
    trainings: [],
    notes: [],
    documents: [],
    sectors: ["University", "Corporate"],
    addedOn: "2026-02-20",
  },
  {
    id: "8",
    code: "ATM-T-008",
    name: "Manish Verma",
    designation: "VLSI & Embedded Systems Trainer",
    photo:
      "https://api.dicebear.com/9.x/notionists/svg?seed=Manish%20Verma&backgroundColor=d7f2e3,e7f6ec,cdeedd",
    phone: "+919845012308",
    whatsapp: "+919845012308",
    email: "manish.verma@example.com",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    organization: "Independent",
    experience: 11,
    trainingExperience: 8,
    trainerType: "Technical Trainer",
    employment: "Freelance",
    modes: ["Offline", "Hybrid"],
    availability: "available",
    rating: 4.75,
    projectsCompleted: 35,
    bio: "Ex-semiconductor engineer turned full-time core trainer in Verilog, FPGA, ARM Cortex and IoT hardware systems.",
    status: "Active",
    tags: ["Core Engineering", "VLSI", "Embedded"],
    skills: [
      { name: "VLSI", level: "Expert", years: 10 },
      { name: "Embedded Systems", level: "Expert", years: 11 },
      { name: "C", level: "Expert", years: 11 },
      { name: "C++", level: "Advanced", years: 8 },
      { name: "MATLAB", level: "Advanced", years: 7 },
    ],
    softSkills: ["Communication"],
    education: [
      {
        degree: "M.Tech",
        specialization: "VLSI Design",
        university: "Manipal University",
        year: 2014,
      },
    ],
    certifications: [],
    trainings: [],
    notes: [],
    documents: [],
    sectors: ["College", "University", "Corporate"],
    addedOn: "2026-01-22",
  },
];

const INITIAL_REQUIREMENTS = [
  {
    id: "req-1",
    code: "REQ-2026-001",
    title: "Java Full Stack Bootcamp",
    client: "ABC University",
    skills: ["Java", "Spring Boot", "SQL", "DSA"],
    min_experience: 5,
    location: "Bangalore",
    mode: "Offline",
    required_trainers: 3,
    start_date: "2026-09-20",
    end_date: "2026-10-02",
    daily_hours: 6,
    sector: "University",
    status: "Open",
    assigned_trainer_ids: ["1"],
    notes: "300 final year engineering students. Need hands-on project mentoring.",
    created_on: "2026-09-01",
  },
  {
    id: "req-2",
    code: "REQ-2026-002",
    title: "AI/ML & Data Engineering Masterclass",
    client: "TechNova Corp",
    skills: ["Python", "Machine Learning", "Data Science", "SQL"],
    min_experience: 6,
    location: "Mysore",
    mode: "Hybrid",
    required_trainers: 2,
    start_date: "2026-09-25",
    end_date: "2026-10-05",
    daily_hours: 4,
    sector: "Corporate",
    status: "In Progress",
    assigned_trainer_ids: ["2"],
    notes: "Upskilling corporate analytics associates.",
    created_on: "2026-09-03",
  },
  {
    id: "req-3",
    code: "REQ-2026-003",
    title: "Campus Placement Readiness & Aptitude",
    client: "RV College of Engineering",
    skills: ["Aptitude", "Interview Skills", "Communication", "Soft Skills"],
    min_experience: 4,
    location: "Bangalore",
    mode: "Offline",
    required_trainers: 2,
    start_date: "2026-10-01",
    end_date: "2026-10-10",
    daily_hours: 8,
    sector: "College",
    status: "Open",
    assigned_trainer_ids: ["6"],
    notes: "Pre-placement training for IT and Core branches.",
    created_on: "2026-09-05",
  },
  {
    id: "req-4",
    code: "REQ-2026-004",
    title: "Cloud & DevOps Architecture Workshop",
    client: "Infosource Global",
    skills: ["AWS", "DevOps", "Linux"],
    min_experience: 8,
    location: "Hyderabad",
    mode: "Online",
    required_trainers: 1,
    start_date: "2026-09-18",
    end_date: "2026-09-22",
    daily_hours: 5,
    sector: "Corporate",
    status: "Fulfilled",
    assigned_trainer_ids: ["4"],
    notes: "Live online hands-on AWS pipelines.",
    created_on: "2026-08-28",
  },
];

async function seed() {
  const db = await mysql.createConnection(dbConfig);
  console.log("Connected to MySQL for seeding...");

  for (const t of INITIAL_TRAINERS) {
    const query = `
      INSERT INTO trainers (
        id, code, name, designation, photo, phone, whatsapp, email,
        city, state, country, organization, experience, training_experience,
        trainer_type, employment, modes, availability, available_from, available_until,
        rating, projects_completed, bio, status, tags, skills, soft_skills,
        education, certifications, trainings, notes, documents, sectors, added_on
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON DUPLICATE KEY UPDATE
        name = VALUES(name),
        designation = VALUES(designation),
        phone = VALUES(phone),
        whatsapp = VALUES(whatsapp),
        email = VALUES(email),
        city = VALUES(city),
        state = VALUES(state),
        experience = VALUES(experience),
        training_experience = VALUES(training_experience),
        trainer_type = VALUES(trainer_type),
        modes = VALUES(modes),
        availability = VALUES(availability),
        rating = VALUES(rating),
        projects_completed = VALUES(projects_completed),
        bio = VALUES(bio),
        status = VALUES(status),
        tags = VALUES(tags),
        skills = VALUES(skills),
        soft_skills = VALUES(soft_skills),
        education = VALUES(education),
        certifications = VALUES(certifications),
        trainings = VALUES(trainings),
        notes = VALUES(notes),
        sectors = VALUES(sectors)
    `;

    const values = [
      t.id,
      t.code,
      t.name,
      t.designation,
      t.photo,
      t.phone,
      t.whatsapp,
      t.email,
      t.city,
      t.state,
      t.country,
      t.organization,
      t.experience,
      t.trainingExperience,
      t.trainerType,
      t.employment,
      JSON.stringify(t.modes),
      t.availability,
      t.availableFrom || null,
      t.availableUntil || null,
      t.rating,
      t.projectsCompleted,
      t.bio,
      t.status,
      JSON.stringify(t.tags),
      JSON.stringify(t.skills),
      JSON.stringify(t.softSkills),
      JSON.stringify(t.education),
      JSON.stringify(t.certifications),
      JSON.stringify(t.trainings),
      JSON.stringify(t.notes),
      JSON.stringify(t.documents),
      JSON.stringify(t.sectors),
      t.addedOn,
    ];

    await db.query(query, values);
  }
  console.log(`Seeded ${INITIAL_TRAINERS.length} trainers into MySQL.`);

  for (const r of INITIAL_REQUIREMENTS) {
    await db.query(
      `INSERT INTO requirements (
        id, code, title, client, skills, min_experience, location, mode,
        required_trainers, start_date, end_date, daily_hours, sector, status,
        assigned_trainer_ids, notes, created_on
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON DUPLICATE KEY UPDATE
        title = VALUES(title),
        client = VALUES(client),
        skills = VALUES(skills),
        min_experience = VALUES(min_experience),
        location = VALUES(location),
        mode = VALUES(mode),
        required_trainers = VALUES(required_trainers),
        start_date = VALUES(start_date),
        end_date = VALUES(end_date),
        daily_hours = VALUES(daily_hours),
        sector = VALUES(sector),
        status = VALUES(status),
        assigned_trainer_ids = VALUES(assigned_trainer_ids),
        notes = VALUES(notes)`,
      [
        r.id,
        r.code,
        r.title,
        r.client,
        JSON.stringify(r.skills),
        r.min_experience,
        r.location,
        r.mode,
        r.required_trainers,
        r.start_date,
        r.end_date,
        r.daily_hours,
        r.sector,
        r.status,
        JSON.stringify(r.assigned_trainer_ids),
        r.notes,
        r.created_on,
      ],
    );
  }
  console.log(`Seeded ${INITIAL_REQUIREMENTS.length} requirements into MySQL.`);

  await db.end();
  console.log("Seeding complete!");
}

seed().catch((err) => {
  console.error("Seeding error:", err);
  process.exit(1);
});
