/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchingIndexRouteImport } from './routes/matching.index'
import { Route as RequirementsIndexRouteImport } from './routes/requirements.index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as TrainersIndexRouteImport } from './routes/trainers.index'
import { Route as TrainersTrainerIdRouteImport } from './routes/trainers.$trainerId'
import { Route as TrainersNewRouteImport } from './routes/trainers.new'
import { Route as TrainersTrainerIdEditRouteImport } from './routes/trainers.$trainerId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingIndexRoute = MatchingIndexRouteImport.update({
  id: '/matching/',
  path: '/matching/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIndexRoute = RequirementsIndexRouteImport.update({
  id: '/requirements/',
  path: '/requirements/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIndexRoute = TrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersTrainerIdRoute = TrainersTrainerIdRouteImport.update({
  id: '/trainers/$trainerId',
  path: '/trainers/$trainerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersNewRoute = TrainersNewRouteImport.update({
  id: '/trainers/new',
  path: '/trainers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersTrainerIdEditRoute = TrainersTrainerIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TrainersTrainerIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trainers/$trainerId': typeof TrainersTrainerIdRouteWithChildren
  '/trainers/new': typeof TrainersNewRoute
  '/matching/': typeof MatchingIndexRoute
  '/requirements/': typeof RequirementsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/trainers/': typeof TrainersIndexRoute
  '/trainers/$trainerId/edit': typeof TrainersTrainerIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trainers/$trainerId': typeof TrainersTrainerIdRouteWithChildren
  '/trainers/new': typeof TrainersNewRoute
  '/matching': typeof MatchingIndexRoute
  '/requirements': typeof RequirementsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/trainers': typeof TrainersIndexRoute
  '/trainers/$trainerId/edit': typeof TrainersTrainerIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trainers/$trainerId': typeof TrainersTrainerIdRouteWithChildren
  '/trainers/new': typeof TrainersNewRoute
  '/matching/': typeof MatchingIndexRoute
  '/requirements/': typeof RequirementsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/trainers/': typeof TrainersIndexRoute
  '/trainers/$trainerId/edit': typeof TrainersTrainerIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trainers/$trainerId'
    | '/trainers/new'
    | '/matching/'
    | '/requirements/'
    | '/skills/'
    | '/trainers/'
    | '/trainers/$trainerId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/trainers/$trainerId'
    | '/trainers/new'
    | '/matching'
    | '/requirements'
    | '/skills'
    | '/trainers'
    | '/trainers/$trainerId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/trainers/$trainerId'
    | '/trainers/new'
    | '/matching/'
    | '/requirements/'
    | '/skills/'
    | '/trainers/'
    | '/trainers/$trainerId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TrainersTrainerIdRoute: typeof TrainersTrainerIdRouteWithChildren
  TrainersNewRoute: typeof TrainersNewRoute
  MatchingIndexRoute: typeof MatchingIndexRoute
  RequirementsIndexRoute: typeof RequirementsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TrainersIndexRoute: typeof TrainersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching/': {
      id: '/matching/'
      path: '/matching'
      fullPath: '/matching/'
      preLoaderRoute: typeof MatchingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements/': {
      id: '/requirements/'
      path: '/requirements'
      fullPath: '/requirements/'
      preLoaderRoute: typeof RequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/': {
      id: '/trainers/'
      path: '/trainers'
      fullPath: '/trainers/'
      preLoaderRoute: typeof TrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$trainerId': {
      id: '/trainers/$trainerId'
      path: '/trainers/$trainerId'
      fullPath: '/trainers/$trainerId'
      preLoaderRoute: typeof TrainersTrainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/new': {
      id: '/trainers/new'
      path: '/trainers/new'
      fullPath: '/trainers/new'
      preLoaderRoute: typeof TrainersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$trainerId/edit': {
      id: '/trainers/$trainerId/edit'
      path: '/edit'
      fullPath: '/trainers/$trainerId/edit'
      preLoaderRoute: typeof TrainersTrainerIdEditRouteImport
      parentRoute: typeof TrainersTrainerIdRoute
    }
  }
}

interface TrainersTrainerIdRouteChildren {
  TrainersTrainerIdEditRoute: typeof TrainersTrainerIdEditRoute
}

const TrainersTrainerIdRouteChildren: TrainersTrainerIdRouteChildren = {
  TrainersTrainerIdEditRoute: TrainersTrainerIdEditRoute,
}

const TrainersTrainerIdRouteWithChildren =
  TrainersTrainerIdRoute._addFileChildren(TrainersTrainerIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TrainersTrainerIdRoute: TrainersTrainerIdRouteWithChildren,
  TrainersNewRoute: TrainersNewRoute,
  MatchingIndexRoute: MatchingIndexRoute,
  RequirementsIndexRoute: RequirementsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TrainersIndexRoute: TrainersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
